# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-10-02 02:54
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20180930_1656'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 10, 2, 2, 54, 3, 825616, tzinfo=utc)),
        ),
    ]
